#!/bin/bash
# 生成keystore文件使用如下命令,这里一定要加上这个 -keyalg rsa ，不然会用默认算法dsa
# keytool -genkey -alias you -keystore app.keystore -validity 4000 -keyalg rsa
KEYSTORE_FILE_NAME=$1
keytool -importkeystore -srckeystore ${KEYSTORE_FILE_NAME} -keyalg rsa -destkeystore tmp.p12 -srcstoretype JKS -deststoretype PKCS12
openssl pkcs12 -in tmp.p12 -nodes -out tmp.rsa.pem
echo "生成的公私秘钥如下："
cat tmp.rsa.pem
privateStart=`grep "BEGIN RSA" tmp.rsa.pem -n|awk '{split($0,b,":");print b[1]}'`
privateEnd=`grep "END RSA" tmp.rsa.pem -n|awk '{split($0,b,":");print b[1]}'`
publicStart=`grep "BEGIN CERT" tmp.rsa.pem -n|awk '{split($0,b,":");print b[1]}'`
publicEnd=`grep "END CERT" tmp.rsa.pem -n|awk '{split($0,b,":");print b[1]}'`
privateStart=$[privateEnd-privateStart+1]
publicStart=$[publicEnd-publicStart+1]
cat tmp.rsa.pem|head -$privateEnd|tail -$privateStart>privatekey.rsa.pem
echo 私钥内容：
cat privatekey.rsa.pem
cat tmp.rsa.pem|head -$publicEnd|tail -$publicStart>publickey.rsa.pem
openssl pkcs8 -topk8 -outform DER -in privatekey.rsa.pem -inform PEM -out privatekey.pk8 -nocrypt
rm tmp.p12 privatekey.rsa.pem
